server:
  port: 3302

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  env: enenv
  user:
    username: ususer
    password: papass
debug: true